### ISSUE TITLE
シークバーのタッチイベントがスムーズでない

### ISSUE THREAD

**Issue by Dai1678** [t-robop/01-Spica-Android#105]
### 概要
- シークバーのつまみをスライドする距離がかなり大きく必要
- 普通はつまみを移動させる位置をタッチすれば簡単に動くのに、移動しない
- APIレベルが高いものはかなりスムーズに動いている

### 想定される解決策
- #103 ですこし調整はしたものの、まだ完全ではなさそう
- API16以下のタブレットのシークバーの動作があやしそうなので、対応するならシークバーを自作する可能性(やりたくない)
- Android 5.0以上の端末ならスムーズに動くっぽいので、タブレット揃えたい...

### リンクとか
- http://www.sumimasen.com/tech/44529489.html
つまみの描画がずれたことがあったので、それの解決方法↑

**Comment by y-ogawara** [comment]
シークバー、作ろう。
