### ISSUE TITLE
囲みブロックの削除の仕様

### ISSUE THREAD

**Issue by TaigaNatto** [t-robop/01-Spica-Android#107]
### 概要
- 現在は囲む系ブロック(if & or)を消した時、中で囲まれてるブロックもまとめて消すようになってる。

### 想定される解決策
- おそらく簡単にいけるのは以下のどれか
1. 今のまま
2. 削除したブロックとその終端ブロックのみ削除
3. 中身まとめて消すか、中身は残すかを選ばせる

**Comment by y-ogawara** [comment]
これは仕様で良いと思う
