### ISSUE TITLE
コマンド送信後のダイアログ・スレッド処理が正常に行われていない時がある

### ISSUE THREAD

**Issue by Dai1678** [t-robop/01-Spica-Android#115]
### 概要
コマンド送信後に実行中のダイアログが閉じない
↓
Android Studioのモニターのネットワーク状態を確認してみた
- UDP送信は正常に行われている

[ESP側からの完了通知を受け取れなかった]
1. ダイアログが開いたままなので、キャンセルボタンを押して閉じる
2. おそらくスレッド処理が正常に終了していない
3. また送信処理を開始すると、前のスレッド処理が動いているまま、さらに受信待機になってアプリが重くなる or クラッシュ

[ESP側からの完了通知が来ているにもかかわらずダイアログが閉じていない]
- モニターのネットワーク状態を見ると、受信データが確認できたにもかかわらずダイアログが閉じられないことがあった

### 想定される解決策
- コードの全見直し、書き直しも十分ありえる
- Asynctaskとか使うのが普通なのでは..?

### リンクとか
-

**Comment by y-ogawara** [comment]
@Kawaguchi410 
これやって！！！

**Comment by y-ogawara** [comment]
疑惑あるけど閉じている気がする
