### ISSUE TITLE
英語版の作成

### ISSUE THREAD

**Issue by y-ogawara** [t-robop/01-Spica-Android#129]
### 概要
- 日本語が全くわからない子がいるため

### 想定される解決策
- stringsファイルを作る
設定画面から言語を変えられるように
全体説明も理解できないからチュートリアル作ったほうが良い？

### リンクとか
-

**Comment by y-ogawara** [comment]
英語版切り替えボタンも！

**Comment by Dai1678** [comment]
#153 で実装完了
