### ISSUE TITLE
アイテムを長押しドラッグではなくタップでドラッグしたい

### ISSUE THREAD

**Issue by TaigaNatto** [t-robop/01-Spica-Android#13]
<img width="290" alt="2018-06-18 19 43 39" src="https://user-images.githubusercontent.com/19305439/41531946-12d82bf2-7330-11e8-967f-9b7fc99bc84a.png">

iPhoneでよくあるような、移動アイコンタップですぐドラッグできるようにしたい

**Comment by ehu-151** [comment]
それって常に画面上にドラッグバーを配置する感じなの？それとも、編集ボタンを押すとドラッグバーが出てくるって感じ？

**Comment by TaigaNatto** [comment]
確かに編集モードで分けるのもアリですけど、スクラッチプログラミングのアプリなら常駐でもいいかと

**Comment by ehu-151** [comment]
menu_list_item.xmlにアイコン追加すればできそう
これやりたいんだけど、どのbranchでやればいいんだ

**Comment by ehu-151** [comment]
そもそも、list_item.xmlで背景の緑の画像を画像にしない方がいいと思う。style.xmlを使用すべき。
[Android　UI基本 Buttonをカスタマイズする](http://tech.pjin.jp/blog/2016/02/09/android%E3%80%80ui%E5%9F%BA%E6%9C%AC-button%E3%82%92%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA%E3%81%99%E3%82%8B/)

これを使えば、移動する用のバーが画像の横幅のせいで窮屈にならないし
将来的に文字サイズを大きくするんだったら、なおさら。

変えるとこ増えた

**Comment by TaigaNatto** [comment]
画像なのはissueにある通り、確かにやらなきゃいけないやつ
実装する機能でBrunch切ってやっていいよ

**Comment by y-ogawara** [comment]
@TaigaNatto これどうなる感じ？

**Comment by y-ogawara** [comment]
@TaigaNatto これどうなっとるや！！！なくなってるならcloseしてくれ

**Comment by TaigaNatto** [comment]
atlasから引き続きの改善として残してあるので、closeはまだです

**Comment by y-ogawara** [comment]
実装が変わったのでclose
