### ISSUE TITLE
コマンドの全体像が見えない

### ISSUE THREAD

**Issue by y-ogawara** [t-robop/01-Spica-Android#15]
00-Atlasの内容と同じ
https://github.com/t-robop/00-Atlas-ac/issues/108

**Comment by TaigaNatto** [comment]
@Kawaguchi410 に任せる
全体像把握Viewの実装 #25

**Comment by y-ogawara** [comment]
@Kawaguchi410 実装終了日記入よろ

**Comment by Dai1678** [comment]
#25 で対応
