### ISSUE TITLE
Dialogの仕様が謎

### ISSUE THREAD

**Issue by TaigaNatto** [t-robop/01-Spica-Android#20]
EditPalamDialogとEditLoopPalamDialogがFragmentManagerに依存してる。
ダイアログ出すだけなら必要無いように思えるので理由を聞きたい。

**Comment by Dai1678** [comment]
@TaigaNatto
両方共DialogFragmentを継承してるからfragmentManagerで管理してるってだけかと

他に実装方法あったっけ

**Comment by TaigaNatto** [comment]
@Dai1678 
そもそもDialogFragmentで継承する必要あるの？
ダイアログ出すだけならAlertDialogとかじゃ駄目なん

**Comment by TaigaNatto** [comment]
@Dai1678 
なるほど。確かにそのほうがいいわ

import元がバラバラで混乱してた。
v4.Fragmentで固定しよう

**Comment by Dai1678** [comment]
基本は全部サポートライブラリの使おう

ちなみにAndroid 9からはandroid.app.Fragment (ネイティブのライブラリ)が非推奨になるので、
android.support.v4.app.Fragment(サポートライブラリ)のを使おうねっていう知見

https://developer.android.com/reference/android/app/FragmentManager
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q13190620238
