### ISSUE TITLE
RecyclerAdapter内でのstrings.xmlに定義した値の呼び出し不可

### ISSUE THREAD

**Issue by Dai1678** [t-robop/01-Spica-Android#23]
strings.xmlから文字列を呼び出すgetStringメソッドがコンテキストを必要とするため、Adapter内でのsetTextに対して適用できていない

`viewHolder.speedRight.setText("右パワー : " + ItemDataArray.get(position).getRightSpeed());
        viewHolder.speedLeft.setText("左パワー : " + ItemDataArray.get(position).getLeftSpeed());
        viewHolder.time.setText(ItemDataArray.get(position).getTime() + "秒");`

**Comment by TaigaNatto** [comment]
引数で渡すか、取得用のメソッド作るか、リスナーで流すかじゃね
