### ISSUE TITLE
NavigationDrawerの実装

### ISSUE THREAD

**Issue by TaigaNatto** [t-robop/01-Spica-Android#29]
### 概要
- どの端末に繋がってるかとか、設定画面や共有画面に飛ばすためのViewがほしい

### 想定される解決策
- NavigationDrawerで問題なさそう

**Comment by Dai1678** [comment]
ユーザーが無意識にドロワー開きそう...

基本俺だけが使う機能だから、ボタン連打の隠しコマンド的なのはどう？

**Comment by TaigaNatto** [comment]
確かに現状運営側しか触らないから、誤操作のほうが多そう。
でもあんまり下手にボタン並べたくないんだよね
