### ISSUE TITLE
UDP通信　受信処理

### ISSUE THREAD

**Issue by Dai1678** [t-robop/01-Spica-Android#30]
### 概要
- 送信ボタンを押した後に全コマンドが完了するまで入力受け付けをストップ
- 全コマンド実行完了後にESP側から返される完了通知で入力受け付けを再開

### 想定される解決策
- 送信ボタンを押した後、受信待機モードに移行・画面入力受け付けをストップ

### 問題点
- 受信するデータの仕様策定

### リンクとか
-

**Comment by kishimotoyk** [comment]
とりあえず機能としては実装できたのでとりあえず閉じる
入力受付ストップしたときに出てくるダイアログのデザインは全くできてない
