### ISSUE TITLE
EditTextとSeekbarを切り替えられるようにする

### ISSUE THREAD

**Issue by TaigaNatto** [t-robop/01-Spica-Android#37]
### 概要
- 現状Seekbarしかないので小中大しか設定できず、forの回数とかifのしきい値の指定ができない

### 想定される解決策
- xmlにviewを書いてvisibleで切り替えられるようにしよう（くそ）

### リンクとか
-

**Comment by Dai1678** [comment]
forの回数とかifのしきい値の指定はEditTextで対応
速度値はシークバーで対応
