### ISSUE TITLE
strings.xmlに文字をまとめる

### ISSUE THREAD

**Issue by multiverse2011** [t-robop/01-Spica-Android#42]
### 概要
- ブロックに表示されている文字類が直書きされている．子供の年齢に応じて表示する文字列を変更できるようにしたほうが良い．

### 想定される解決策
-BlockModelの中にちょいちょいおる．

### リンクとか
-

**Comment by y-ogawara** [comment]
@TaigaNatto が書いているテキストを書き換える必要がありそうなのでAに
