### ISSUE TITLE
全ブロックのパラメータが同一のものになっている

### ISSUE THREAD

**Issue by Dai1678** [t-robop/01-Spica-Android#50]
### 概要
前進ブロックや後退ブロックなどの全てのブロックにおけるシークバーの値が同一になってしまっている。

### 想定される解決策
- ブロック追加時に既存データをロードしている？

### リンクとか
-

**Comment by TaigaNatto** [comment]
データの中身もViewの保持してる情報も正常だったので、onStartに書くことで解決。onViewCreatedと描画周りでバグってたっぽい
