### ISSUE TITLE
回転ブロックの左or右を変更するスイッチの状態管理ができていない

### ISSUE THREAD

**Issue by Dai1678** [t-robop/01-Spica-Android#51]
### 概要
- 回転ブロックのスイッチ (左or右を切り替えるやつ) が設定Fragmentを開くたびにOFFで初期化されている
- 回転ブロックの画像は変わっている (正常)

### 想定される解決策
- データ管理されてなさそう

### リンクとか
-

**Comment by TaigaNatto** [comment]
現状だとそういう仕様だからバグじゃない
OFFで初期化して、今と逆にしたかったらチェックするかんじ

**Comment by y-ogawara** [comment]
だいさくの仕様で実装して

**Comment by y-ogawara** [comment]
ラジオボタンにして

**Comment by Dai1678** [comment]
ラジオボタンで実装完了
データも正常
