### ISSUE TITLE
ifブロックの条件指定

### ISSUE THREAD

**Issue by TaigaNatto** [t-robop/01-Spica-Android#65]
### 概要
- いまは「10cm」みたいなデータは持ってるけど、それ以上と以下のどちらでTrueに行くのかがわからない

### 想定される解決策
- マガルブロック同様、ifブロックでも２つ選択できるようにしよう

### リンクとか
-

**Comment by Dai1678** [comment]
ifスタートブロックのleftSpeedにセットする仕様を送信コマンド生成処理のところが適用できてなかった

@Dai1678
