### ISSUE TITLE
block設定画面のデザインが実装されてない

### ISSUE THREAD

**Issue by y-ogawara** [t-robop/01-Spica-Android#84]
### 概要
- @TaigaNatto がキレイに実装するって言ってた。されてない。

### 想定される解決策
- 

### リンクとか
-

**Comment by multiverse2011** [comment]
![image](https://user-images.githubusercontent.com/12444722/47539777-eb944d80-d90c-11e8-83f4-7fafcf5d6e3b.png)

## 現状のデザインの問題点
- ループの回数で小数点表示が存在する．
- ポップアップで出てきたウインドウに表示される情報が少なすぎる．Ex)"ループ"としか表示されていない．
- ポップアップウィンドウがわかりにくい（ポップアップウィンドウがアクティブであると認識しにくい）．後ろに表示されるblockの線と同化してしまっていて見にくい．
- 保存，キャンセル，削除とテキストでの表示しかないがアイコンも表示したほうがいいのでは．色も削除にしかついていないのでポジティブボタンがわかりにくい．

**Comment by Dai1678** [comment]
#100 までで修正完了した問題点
- ループの回数で小数点表示が存在する．
- ループブロックの画像(黄色)が見づらいのでオレンジ色に近い画像に差し替え (古い画像は~_old.pngで残している)

**Comment by Dai1678** [comment]
#120 で実装完了
