### ISSUE TITLE
if分岐のTrue Falseの表示

### ISSUE THREAD

**Issue by multiverse2011** [t-robop/01-Spica-Android#90]
### 概要
![image](https://user-images.githubusercontent.com/12444722/47540369-d4a32a80-d90f-11e8-8479-e34aeb69fd58.png)

- どっちのレーンがTrue，Falseなのかわからない

### 想定される解決策
- 

### リンクとか
-

**Comment by TaigaNatto** [comment]
いったんラベル貼ったけど完璧に解決してない

**Comment by Dai1678** [comment]
ラベルの文言修正が必要

**Comment by Dai1678** [comment]
ラベルの文言について、
日本語は 「はい」「いいえ」
英語は「Yes」「No」
で設定済み
