### ISSUE TITLE
ESPのリブート中にキャンセル処理を送るとクラッシュする

### ISSUE THREAD

**Issue by Dai1678** [t-robop/01-Spica-Android#95]
### 概要
- なんらかの状況でコマンドの送信ができていない
- sendDataの生成はできている
- ESP側がsendDataを受け取れていない

### 想定される解決策
- アプリアンインストールしたらなおった

### リンクとか
-

**Comment by Dai1678** [comment]
ESPのreboot中に連続でreboot処理をリクエストするとESP側がクラッシュするので、アプリ側でもその後の動作が受け付けられなくなってしまう

reboot中に再度リクエストできないようにする

**Comment by Dai1678** [comment]
CancelおしたらCancel中・・・みたいに2秒くらいアプリ側で送信できなくする(ダイアログじゃなくてもいい)
by 西村

**Comment by TaigaNatto** [comment]
いま実装中
まだバグってるから検証を続けてほしい

**Comment by multiverse2011** [comment]
![image](https://user-images.githubusercontent.com/12444722/47886716-22271680-de7f-11e8-9c1d-2f6c0115d739.png)
やはりRTCメモリのリセットを任意でやれば解決するのでは
http://okiraku-camera.tokyo/blog/?p=7129

**Comment by multiverse2011** [comment]
この問題，ESP側の問題なのでこっちに統合
https://github.com/t-robop/01-Spica-hw/issues/39#issuecomment-437641144
